#!/usr/bin/env bash
# Regenerate packages/ennio/prebuilt/manifest.json from the current contents
# of packages/ennio/prebuilt/. CI runs this after building all slices so the
# published npm tarball ships a fresh manifest. Local devs run it after
# rebuilding a single slice to refresh the SHA-256 the CLI verifies before
# dlopen.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
DIR="$ROOT/prebuilt"

if [[ ! -d "$DIR" ]]; then
    echo "No prebuilt/ directory at $DIR" >&2
    exit 1
fi

sha_for() {
    shasum -a 256 "$1" | awk '{print $1}'
}

SHIM="$DIR/libennio-shim.dylib"
if [[ ! -f "$SHIM" ]]; then
    echo "Missing shim at $SHIM. Run build-shim.sh first." >&2
    exit 2
fi

OUT="$DIR/manifest.json"
{
    echo "{"
    echo "  \"\$comment\": \"Generated by scripts/regen-manifest.sh. CLI verifies each dylib's SHA-256 against this manifest before dlopen.\","
    echo "  \"schema\": 1,"
    echo "  \"shim\": {"
    echo "    \"file\": \"libennio-shim.dylib\","
    echo "    \"sha256\": \"$(sha_for "$SHIM")\""
    echo "  },"
    echo "  \"slices\": {"
    first=1
    for slice in "$DIR"/libennio-rn*-sim.dylib; do
        [[ -f "$slice" ]] || continue
        ver=$(basename "$slice" | sed -E 's/^libennio-rn(.+)-sim\.dylib$/\1/')
        h=$(sha_for "$slice")
        if [[ $first -eq 0 ]]; then echo ","; fi
        first=0
        printf '    "%s": { "file": "%s", "sha256": "%s" }' "$ver" "$(basename "$slice")" "$h"
    done
    echo ""
    echo "  }"
    echo "}"
} > "$OUT"

echo "Wrote $OUT"
cat "$OUT"
